mod "boxen",      "3.9.1", :github_tarball => "boxen/puppet-boxen"
mod "homebrew",   "2.1.0", :github_tarball => "boxen/puppet-homebrew"
mod "stdlib",     "4.9.0", :github_tarball => "puppetlabs/puppetlabs-stdlib"
